apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runners-stream-ci
spec:
  replicas: 2
  template:
    spec:
      image: 'summerwind/actions-runner-dind:tag-placeholder'
      dockerdWithinRunnerContainer: true
      priorityClassName: high-priority
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: stream-metadata-default
      repository: spring-cloud/stream-applications
      githubAPICredentialsFrom:
        secretRef:
          name: controller-manager
      resources:
        requests:
          cpu: "1500m"
          memory: "1536Mi"
      labels:
        - stream-ci
