apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runners-stream-ci
spec:
  template:
    spec:
      image: 'summerwind/actions-runner-dind:tag-placeholder'
      priorityClassName: high-priority
      dockerdWithinRunnerContainer: true
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: stream-metadata-default
      repository: spring-cloud/stream-applications
      githubAPICredentialsFrom:
        secretRef:
          name: controller-manager-secret
      resources:
        requests:
          cpu: "1500m"
          memory: "1536Mi"
      labels:
        - stream-ci
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runners-stream-ci-scaling
spec:
  githubAPICredentialsFrom:
    secretRef:
      name: controller-manager-secret
  minReplicas: min-replicas-placeholder
  maxReplicas: max-replicas-placeholder
  scaleTargetRef:
    kind: RunnerDeployment
    name: runners-stream-ci
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "30m"
