apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runners-stream-ci-large
spec:
  template:
    spec:
      repository: spring-cloud/stream-applications
      image: 'summerwind/actions-runner-dind:tag-placeholder'
      priorityClassName: high-priority
      dockerdWithinRunnerContainer: true
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: stream-metadata-default
      githubAPICredentialsFrom:
        secretRef:
          name: controller-manager
      resources:
        requests:
          cpu: "3000m"
          memory: "3Gi"
      labels:
        - stream-ci-large
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runners-stream-ci-large-scaling
spec:
  githubAPICredentialsFrom:
    secretRef:
      name: controller-manager
  minReplicas: 0
  maxReplicas: 2
  scaleTargetRef:
    kind: RunnerDeployment
    name: runners-stream-ci-large
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "20m"
