syncPeriod: 2m
authSecret:
  create: false
  name: controller-manager
priorityClassName: high-priority
imagePullSecrets:
  - name: scdf-metadata-default
githubWebhookServer:
  priorityClassName: high-priority
  secret:
    name: controller-manager
  enabled: true
image:
  tag: v0.27.0
runner:
  statusUpdateHook:
    enabled: true
